name: Metrics

on:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight UTC
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # ======================
      # ğŸ“… Isometric Calendar
      # ======================
      - name: ğŸ“… Isometric Calendar (Full Year)
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.GH_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      # ======================
      # ğŸ† Achievements
      # ======================
      - name: ğŸ† Achievements
        uses: lowlighter/metrics@latest
        continue-on-error: true
        with:
          filename: metrics.plugin.achievements.svg
          token: ${{ secrets.GH_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_threshold: B
          plugin_achievements_secrets: yes

      # ======================
      # ğŸ’¡ Coding Habits
      # ======================
      - name: ğŸ’¡ Coding Habits
        uses: lowlighter/metrics@latest
        continue-on-error: true
        with:
          filename: metrics.plugin.habits.svg
          token: ${{ secrets.GH_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: no
          plugin_habits_from: 100

      # ======================
      # ğŸˆ·ï¸ Languages
      # ======================
      - name: ğŸˆ·ï¸ Languages Activity
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.GH_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
